/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import timestamp.Dado;
import timestamp.Operacao;
import timestamp.Operador;
import timestamp.SGBD;
import timestamp.Tabela;
import timestamp.TipoOperacao;
import timestamp.Transacao;

/**
 *
 * @author Adriano
 */
public class Tela extends javax.swing.JFrame {

    private SGBD sgbd;
    private Operador operador;

    private Tabela tabela;
    private Dado[] dados;
    private ArrayList<Transacao> escalonamento;

    /**
     * Creates new form Tela
     */
    public Tela(SGBD sgbd, Tabela tabela, Operador operador) {
        this.sgbd = sgbd;
        this.operador = operador;
        this.tabela = tabela;
        this.dados = tabela.getDados();
        this.escalonamento = sgbd.getEscalonamento();

        initComponents();
    }

    public void atualizarTela() {

        this.apresentarDados();
        this.popularLog();
//        this.apresentarTransacoes();
    }

    public void apresentarDados() {
        DefaultTableModel dtmDados = (DefaultTableModel) tbDados.getModel();

        Object coluna[] = new Object[5];

        for (int i = 0; i < dados.length; i++) {
            
            String transacoesWait = new String();
            ArrayList<Transacao> filaWait = dados[i].getFilaWait();
            
            for (Transacao transacao : filaWait) {
                transacoesWait = transacoesWait + "T" + transacao.getId() + "  ";
            }
            
            coluna[0] = dados[i].getNome();
            coluna[1] = dados[i].getValor();
            coluna[2] = dados[i].getTSread();
            coluna[3] = dados[i].getTSwrite();
            coluna[4] = transacoesWait;
            dtmDados.addRow(coluna);
        }
    }
    public void apresentarTransacoes() {
        DefaultTableModel dtmTransacoes = (DefaultTableModel) tbTransacoes.getModel();

        Object coluna[] = new Object[8];

        for (Transacao transacao : escalonamento) {
            
            ArrayList<Operacao> operacoes = transacao.getOperacoes();
            
            coluna[0] = "T" + transacao.getId();
            
            for (int i = 0; i < operacoes.size(); i++) {
                TipoOperacao tipo = operacoes.get(i).getTipo();
                char dado = operacoes.get(i).getDado();
                int valor = operacoes.get(i).getValor();
                
                coluna[i + 1] = tipo + "(" + dado + ", " + valor + ")";
                
            }
            dtmTransacoes.addRow(coluna);
        }
    }

    public void popularLog() {
        ArrayList<Operacao> operacoes = sgbd.getLog();
        String log = new String();
        TipoOperacao tipo;
        long idTransacao;
        char dado;
        int valor;
        long ts;
        int i = 1;

        for (Operacao operacao : operacoes) {
            tipo = operacao.getTipo();
            idTransacao = operacao.getIdTransacao();
            dado = operacao.getDado();
            valor = operacao.getValor();
            ts = operacao.getTimeStamp();

            log = log + i + ". ";
            log = log + tipo + idTransacao;

            if (tipo == TipoOperacao.R) {
                log = log + "(" + dado + ", " + valor + "); TS: " + ts + ";"
                        + System.getProperty("line.separator");
            } else if (tipo == TipoOperacao.W) {
                log = log + "(" + dado + ", " + valor + "); TS: " + ts + ";"
                        + System.getProperty("line.separator");
            } else {
                log = log + ";" + System.getProperty("line.separator");
            }
            i++;
        }
        taLog.setText(log);

    }

    public void limparDados() {
        DefaultTableModel dtmDados = (DefaultTableModel) tbDados.getModel();
        for (int i = tbDados.getRowCount() - 1; i >= 0; i--) {
            dtmDados.removeRow(i);
        }
//        DefaultTableModel dtmTransacoes = (DefaultTableModel) tbTransacoes.getModel();
//        for (int i = tbTransacoes.getRowCount() - 1; i >= 0; i--) {
//            dtmTransacoes.removeRow(i);
//        }
    }

    public void atualizarProxima(String proxima) {
        tfProxima.setText(proxima);
    }

    public void inativar() {
        btProxima.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        taLog = new javax.swing.JTextArea();
        btProxima = new javax.swing.JButton();
        tfProxima = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTransacoes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TS-Estrito");
        setResizable(false);

        tbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dado", "Valor", "TS-Read", "TS-Write", "Fila-WAIT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDados);

        taLog.setEditable(false);
        taLog.setColumns(20);
        taLog.setRows(5);
        jScrollPane2.setViewportView(taLog);

        btProxima.setText("Próxima");
        btProxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximaActionPerformed(evt);
            }
        });

        tfProxima.setEditable(false);
        tfProxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProximaActionPerformed(evt);
            }
        });

        tbTransacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "", "", "", "", "", "", ""
            }
        ));
        jScrollPane3.setViewportView(tbTransacoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btProxima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfProxima, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btProxima)
                            .addComponent(tfProxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfProximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProximaActionPerformed

    private void btProximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximaActionPerformed
        operador.executar();
    }//GEN-LAST:event_btProximaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProxima;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea taLog;
    private javax.swing.JTable tbDados;
    private javax.swing.JTable tbTransacoes;
    private javax.swing.JTextField tfProxima;
    // End of variables declaration//GEN-END:variables

}
